name: Build image and deploy
on:
#  push:
#    branches:
#      - master
  pull_request:
      branches: 
      - master

env:
  PROJECT_ID: tensile-will-419716
  GKE_CLUSTER: diploma
  GKE_ZONE: us-central1-a
  IMAGE_NAME: java_app
  USE_GKE_GCLOUD_AUTH_PLUGIN: True

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.REGISTRY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - run: |-
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Dump GCP environment config
      run: |-
        gcloud info
        gcloud auth configure-docker us-central1-docker.pkg.dev
#        gcloud --quiet auth configure-docker

    - name: Docker Build
      run: |-
        docker build --tag "us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GITHUB_SHA" .
        docker tag "us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GITHUB_SHA" "us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest"

    - name: Publish
      run: |-
        docker push "us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GITHUB_SHA"
        docker push "us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest"

    - name: Deploy
      run: |-
        DEPLOY_IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GITHUB_SHA
        sed -i 's|$DEPLOY_IMAGE|'"$DEPLOY_IMAGE"'|g' ./k8s/deployment.yml
        kubectl apply -f k8s/deployment.yml
#        kubectl rollout status --namespace=java-application -w deployment/placement-api

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}